### ISSUE TITLE
Doesn't work on Update 5

### ISSUE THREAD

**Issue by 19wolf** [ihsoft/TimberbornMods#13]
Unless I'm missing a step somewhere, I don't see any gui or anything indicating Automation and Smart Power are working

**Comment by ihsoft** [comment]
For U5 TimberAPi needs to be updated to 0.6.2 (go to Mod.io and choose "other versions"). With it, Smart Power works just fine (verified). However, Automation mod fails due to game's core module changes ([bug](https://github.com/ihsoft/TimberbornMods/issues/14)).

**Comment by 19wolf** [comment]
Seems to be working
