### ISSUE TITLE
[Automation] Allow automations during badtides.

### ISSUE THREAD

**Issue by 19wolf** [ihsoft/TimberbornMods#16]
I would love to be able to open/close floodgates during badtide- separately from during droughts. Example: 

Gate1 - set to 0 at badtide
Gate1 - set to 0.5 at drought
Gate1 - set to 1 at normal
Gate2 - set to 0 at normal 
Gate2 set to .5 at drought
Gate2 - set to 1 at badtide
etc

**Comment by ihsoft** [comment]
The badtide support is now there. However, the actual rules need to be made and tested.

**Comment by ihsoft** [comment]
Implemeted since `v0.9`
