### ISSUE TITLE
[Automation] broken on U5 v0.5.4.0

### ISSUE THREAD

**Issue by kamigari84** [ihsoft/TimberbornMods#19]
Dynamite drill down is currently broken ... something about Coordinates?
It doesn't even show up ingame

Here is the logged error and warnings:

> [Error  :Automation] Failed: Could not load type of field 'Automation.Actions.DetonateDynamiteAction+DetonateAndRepeatRule:BlockObjectToolPlace' (0) due to: Could not resolve type with token 01000085 from typeref (expected class 'Timberborn.Coordinates.OrientedCoordinates' in assembly 'Timberborn.Coordinates, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null') assembly:Timberborn.Coordinates, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null type:Timberborn.Coordinates.OrientedCoordinates member:(null)
> ...
> [Warning:  HarmonyX] AccessTools.GetTypesFromAssembly: assembly Automation, Version=0.9.8673.32230, Culture=neutral, PublicKeyToken=null => System.Reflection.ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
> Could not load type of field 'Automation.Actions.DetonateDynamiteAction+DetonateAndRepeatRule:BlockObjectToolPlace' (0) due to: Could not resolve type with token 01000085 from typeref (expected class 'Timberborn.Coordinates.OrientedCoordinates' in assembly 'Timberborn.Coordinates, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null') assembly:Timberborn.Coordinates, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null type:Timberborn.Coordinates.OrientedCoordinates member:(null)
>   at (wrapper managed-to-native) System.Reflection.Assembly.GetTypes(System.Reflection.Assembly,bool)
>   at System.Reflection.Assembly.GetTypes () [0x00000] in <cb3602b5bf2148caa08db7780ec02b19>:0 
>   at HarmonyLib.AccessTools.GetTypesFromAssembly (System.Reflection.Assembly assembly) [0x0000d] in <474744d65d8e460fa08cd5fd82b5d65f>:0 
> System.TypeLoadException: Could not load type of field 'Automation.Actions.DetonateDynamiteAction+DetonateAndRepeatRule:BlockObjectToolPlace' (0) due to: Could not resolve type with token 01000085 from typeref (expected class 'Timberborn.Coordinates.OrientedCoordinates' in assembly 'Timberborn.Coordinates, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null') assembly:Timberborn.Coordinates, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null type:Timberborn.Coordinates.OrientedCoordinates member:(null)
> ...
> [Warning:  HarmonyX] AccessTools.GetTypesFromAssembly: assembly Automation, Version=0.9.8673.32230, Culture=neutral, PublicKeyToken=null => System.Reflection.ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
> Could not load type of field 'Automation.Actions.DetonateDynamiteAction+DetonateAndRepeatRule:BlockObjectToolPlace' (0) due to: Could not resolve type with token 01000085 from typeref (expected class 'Timberborn.Coordinates.OrientedCoordinates' in assembly 'Timberborn.Coordinates, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null') assembly:Timberborn.Coordinates, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null type:Timberborn.Coordinates.OrientedCoordinates member:(null)
>   at (wrapper managed-to-native) System.Reflection.Assembly.GetTypes(System.Reflection.Assembly,bool)
>   at System.Reflection.Assembly.GetTypes () [0x00000] in <cb3602b5bf2148caa08db7780ec02b19>:0 
>   at HarmonyLib.AccessTools.GetTypesFromAssembly (System.Reflection.Assembly assembly) [0x0000d] in <474744d65d8e460fa08cd5fd82b5d65f>:0 
> System.TypeLoadException: Could not load type of field 'Automation.Actions.DetonateDynamiteAction+DetonateAndRepeatRule:BlockObjectToolPlace' (0) due to: Could not resolve type with token 01000085 from typeref (expected class 'Timberborn.Coordinates.OrientedCoordinates' in assembly 'Timberborn.Coordinates, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null') assembly:Timberborn.Coordinates, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null type:Timberborn.Coordinates.OrientedCoordinates member:(null)
> [Warning:  HarmonyX] AccessTools.GetTypesFromAssembly: assembly Automation, Version=0.9.8673.32230, Culture=neutral, PublicKeyToken=null => System.Reflection.ReflectionTypeLoadException: Exception of type 'System.Reflection.ReflectionTypeLoadException' was thrown.
> Could not load type of field 'Automation.Actions.DetonateDynamiteAction+DetonateAndRepeatRule:BlockObjectToolPlace' (0) due to: Could not resolve type with token 01000085 from typeref (expected class 'Timberborn.Coordinates.OrientedCoordinates' in assembly 'Timberborn.Coordinates, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null') assembly:Timberborn.Coordinates, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null type:Timberborn.Coordinates.OrientedCoordinates member:(null)
>   at (wrapper managed-to-native) System.Reflection.Assembly.GetTypes(System.Reflection.Assembly,bool)
>   at System.Reflection.Assembly.GetTypes () [0x00000] in <cb3602b5bf2148caa08db7780ec02b19>:0 
>   at HarmonyLib.AccessTools.GetTypesFromAssembly (System.Reflection.Assembly assembly) [0x0000d] in <474744d65d8e460fa08cd5fd82b5d65f>:0 
> System.TypeLoadException: Could not load type of field 'Automation.Actions.DetonateDynamiteAction+DetonateAndRepeatRule:BlockObjectToolPlace' (0) due to: Could not resolve type with token 01000085 from typeref (expected class 'Timberborn.Coordinates.OrientedCoordinates' in assembly 'Timberborn.Coordinates, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null') assembly:Timberborn.Coordinates, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null type:Timberborn.Coordinates.OrientedCoordinates member:(null)

**Comment by ihsoft** [comment]
Fixed in `0.10`.
