### ISSUE TITLE
[TimberCommons] Water tower with zero coverage consumes water

### ISSUE THREAD

**Issue by ihsoft** [ihsoft/TimberbornMods#37]
IF the tower cannot irrigate anything, it must not consume water.

**Comment by KnatteAnka** [comment]
consume no power or Water.

Example scenario:
![image](https://github.com/ihsoft/TimberbornMods/assets/10638776/0ec85869-ddff-4110-91bd-b1f5ce838f33)
building built so it cant irrigate anything
![image](https://github.com/ihsoft/TimberbornMods/assets/10638776/f6773b03-e5df-4eb5-a866-4cd64d895624)


maybe show an error message that no tiles connected to irrigate
could use base game icon: CultivationHalted
![image](https://github.com/ihsoft/TimberbornMods/assets/10638776/bdbf36be-4f87-42a6-95c7-73c05b847a33)
