### ISSUE TITLE
Ironteeth Bots not Charging

### ISSUE THREAD

**Issue by jmtarrant00** [ihsoft/TimberbornMods#47]
While using Smart Power, Iron Teeth Bots don't properly charge when the charging stations are idle at 0hp. Occasionally bots will go into a charging station for a fraction of a second. Disabling the mod made all unpowered bots run to the closest charging station

**Comment by ihsoft** [comment]
This is likely this case: https://github.com/ihsoft/TimberbornMods/wiki/Smart-Power#edge-case-no-active-consumers-in-the-network. If all consumers go to saving mode, then all engines stop and the network is treated as unpowered. To solve it, add a battery or select one engine for always running. Please, let me know if it resolves the issue.

**Comment by ihsoft** [comment]
I assume it was the case.
