### ISSUE TITLE
Possible issue - game freezing periodically when powered building selected

### ISSUE THREAD

**Issue by HugePinball** [ihsoft/TimberbornMods#8]
Possible issue with this mod: on more than one world now, sometimes if I had a powered workshop selected, the game will freeze every several seconds (very much like when it autosaves).  I seem to have only noticed it at later stages, so possibly related to number of buildings/batteries? (I've had a lot of small flywheels from the flywheels mod.)  Disabling this mod appears to stop this issue, and re-enabling it appears to make it return.  Perhaps something to investigate.

Attaching most recent save where I noticed this.  Let me know if I can provide any further info.

[timbersave.zip](https://github.com/ihsoft/TimberbornMods/files/12445373/timbersave.zip)

**Comment by ihsoft** [comment]
Interesting. `SmartPower` only creates UI fragment for the engines. It should not affect any powered building. Do you observer this behavior when selecting a power shaft?

**Comment by HugePinball** [comment]
No, only powered buildings.  It's also intermittent, that is sometimes having buildings selected no freezing occurs, but when it does it persists for some time, and freezes at what seems to be regular intervals every several seconds - deselecting stops the freezing, and selecting the same or any other building starts the freezing again.

Since it is intermittent, I'm gonna try running a longer session without SmartPower enabled just to see if it does crop up again.

**Comment by ihsoft** [comment]
Indeed, I see this freeze. It seems to me, it happens at particular times of the day (game time). Did you notice any patterns?

Your game is pretty heavily modded, so it may be a mods conflict. Could you please share the log file? Also, could you please try to remove all the non-critical mods and check if the problem happens? I tried to remove some, but it broke the city :)

**Comment by HugePinball** [comment]
Oh, good - well confirmation is good.  Was going to report I had a few hours session without SmartPower and did not see the freezing occur.

Yes, I will try without other mods.  First I will just try without [AutoRecipe](https://mod.io/g/timberborn/m/autorecipe), as this seemed like the next likely culprit based on what it does.  If that doesn't tell us anything I may just start a fresh world with no other mods.

Which log files are you looking for specifically?

**Comment by HugePinball** [comment]
Also, I can't say I noticed a pattern, but I hadn't really been looking for one.  I'll try to pay attention to time of day.

**Comment by ihsoft** [comment]
Please, check on the newer version (`1.4`). I don't see freezes on it, but the fix is not really fixing anything. It just otimizes the code a bit.
